<?php
	        if(!$_REQUEST['content']){
		        $meta_titulo = 'Diseño de Páginas Web';
		        $meta_descripcion = 'Somos efectivos en la producción de resultados a través de nuestras estrategias de marketing digital.';
		        $meta_keywords = 'agencia digital,Email Marketing,diseno de paginas web,marketing online,community managers,marketing digital,diseno paginas web,desarrolladores paginas web,paginas web colombia';
	        }elseif($_REQUEST['content']=='desarrollo-web'){
		        $meta_titulo = 'Desarrollo Web';
		        $meta_keywords = '
desarrollos web,diseño y desarrollo web,desarrollador paginas web,desarrollo de pagina web,desarrollo páginas web,empresas de desarrollo web,desarrollo de web,desarrollo de páginas web,desarrollo aplicaciones web,empresa desarrollo web,desarrolladores web,empresas de web,desarrollador web,desarrollo web bogota,diseño desarrollo web,diseño y desarrollo de sitios web,desarrollo web php,desarrollo web profesional,desarrollo de sitio web,empresas de desarrollo de paginas web,empresa de desarrollo web,desarrollo y diseño web,desarrollo y diseño de paginas web,desarrollador web freelance,desarrollos de paginas web,desarrolladores de paginas web,desarrollo de paginas web colombia,paginas web desarrollo,desarrollo de paginas web,desarrollar paginas web,desarrollo paginas web bogota,desarrollo web en bogota,desarrollo de paginas web bogota,web bogota,desarrolladores paginas web bogota,dsarrollo web,empresas de desarrollo paginas web colombia,desarrollo paginas web,sdesarrollo paginas web bogota,creacion de sitios web,desarrollo pagina web,propuesta para el desarrollo de un sitio web,técnico en desarrollo de sitios web bogotá,desarrollo paginas web responsive,diseño y desarrollo web con html5 y css bogota,programacion y paginas wed';
		        $meta_descripcion = 'Desarrollo de sitios y aplicaciones web con orientación a resultados. Soporte a través de nuestro sistema helpdesk. Adaptabilidad a dispositivos móviles.';
	        }elseif($_REQUEST['content']=='paginas-web'){
		        $meta_titulo = "Páginas Web";
		        $meta_keywords = "busco paginas web,comprar paginas web,construccion paginas web,construir paginas web,cotizacion paginas web,cotizaciones paginas web,cpnstruccion paginas web bogota,diseño de paginas,diseño paginas,diseño paginas sencillas,diseño paginas web colombia,elaboracion de paginas web bogota zona norte,elaboracion paginas web,elaboracion paginas web bogota contactos,hacemos paginas web,hay empresas que hagan paginas web,los valores paginas web,maquetacion de paginas web,marketing de paginas web,nombre de empresas que hagan paginas web en bogota,pagimas web,paginas de internet,páginas web,paginas web a todo costo colombia,paginas web administrables,paginas web autoadministrables,paginas web bogot,paginas web bogota,páginas web bogota,páginas web bogotá,paginas web bogota colombia,paginas web colombia,paginas web colombuia,paginas web comerciales,paginas web corporativas,paginas web costo colombia,paginas web dinamicas,paginas web diseño,paginas web economicas bogota,paginas web en bogota,paginas web en bogota colombia,paginas web en bucaramanga,paginas web en colombia,páginas web en colombia,paginas web en html,páginas web en html,páginas web innovadoras,paginas web interactivas,paginas web medellin,paginas web modernas,paginas web online,páginas web para empresas,paginas web para pymes,paginas web precios,paginas web profesionales,paginas web que venden,paginas web sencillas,paginas webs,planes de paginas web,precio de paginas web,precio paginas web,precios de paginas web,precios de paginas web bogota,precios paginas web,precios paginas web colombia,proveedores paginas web,quien hace paginas web,quien hace paginas web bogota,realizacion de increibles paginas web,realizacion de paginas web bogota,realizacion paginas web,servicio de paginas web,venta de paginas web bogota colombia";
		        $meta_descripcion = "Páginas web adaptables a dispositivos móviles, con orientación a resultados y soporte anual.";
	        }elseif($_REQUEST['content']=="empresas-paginas-web"){
		        $meta_titulo="Empresa de Diseño de Páginas Web";
		        $meta_keywords="empresa de paginas web,empresa paginas web,empresas de paginas web,empresas de paginas web,empresas páginas web,empresas publicitarias de paginas web,empresas que hacen paginas web,empresas que hacen paginas web en bogota,empresa de diseño de páginas web,empresa diseñadora de paginas web,empresa diseño páginas web,empresas de diseño de paginas web,empresas de diseño de paginas web en bogota,empresas diseñadoras de paginas web,empresas diseño páginas web,empresas que diseñan paginas web,empresas que diseñan paginas web en bogota,empresa de pagina web";
			   $meta_descripcion="Somos una empresa dedicada al desarrollo de soluciones de marketing digital y desarrollo web empresariales.";
	        }elseif($_REQUEST['content']=='creacion-de-sitios-web'){
		        $meta_titulo="Creación de Sitios Web";
		        $meta_keywords="creacion de paginas web,creacion páginas web,empresas que creen paginas web,creacion paginas web bogota,creación de paginas web,creacion de paginas web bogota,creacion paginas web precio,cracion de paginas web,creador de paginas web,creamos paginas web,creacion de paginas web con base de datos,empresas creadoras de paginas web,empresas que crean paginas web,empresas creacion paginas web,empresas de creacion de paginas web,creador de paginas web bogota,empresa que crea paginas web,creacion de paginas web,creacion paginas web,precio creacion de paginas web,empresas creadoras de paginas web en bogota,empresas colombianas para creación de paginas web,empresas creadoras de sitios web,empresas que crean pagina web,creador de páginas web,creadores de paginas web,creadores paginas web";
		        $meta_descripcion="Creación de sitios web corporativos orientados a resultados, con adaptabilidad a tabletas y teléfonos inteligentes. Soporte anual a través de nuestro avanzado sistema Helpdesk.";
	        }elseif($_REQUEST['content']=='diseno-paginas-web'){
		        $meta_titulo="Diseño de Páginas Web";
		        $meta_keywords="administrador de paginas web,costo de diseño de paginas web colombia,costos de diseño de un pagina web para colombia,desarrollo diseño paginas web bogota,diseñador de pagina web bogota,disenador de paginas web,diseñador de paginas web,diseñador pagina web,diseñador páginas web,disenadores de paginas web,diseñadores de paginas web,disenadores de paginas web bogota,diseñadores de paginas web bogota,diseñadores de paginas web en bogota,diseñadores paginas web,diseñadores páginas web,diseñadores paginas web bogota,diseñamos paginas web,diseñar paginas web,diseño de pag web,diseño de pagina sweb,diseño de páginas,diseno de paginas web,diseño de paginas web,diseño de páginas web,diseno de paginas web bogota,diseño de paginas web bogota,diseño de paginas web bogota html5,diseño de paginas web colombia,diseño de paginas web en bogota,diseño de paginas web en bogota colombia,diseño de paginas web en html,diseño de paginas web en medellin,diseño de paginas web online,diseño de paginas web para empresas,diseño de paginas web para niños,diseño de paginas web precio,diseño de paginas web precios,diseño de paginas web sitios,diseño de páginas y sitios web,diseno de paginass web,diseño de paguinas web,diseño de sitios web en wordpress,diseño de una página web,diseño depaginas web,diseño pag web,diseño pagina web bogota,diseño pagina web colombia,diseño páginas sitios web,diseno paginas web,diseño páginas web,diseño paginas web administrables bogota,diseno paginas web bogota,diseño paginas web bogota,diseño paginas web empresas,diseño paginas web precio,diseño paginas web precios,diseño páginas web profesionales,diseño paginas webs,diseño para paginas web,diseño web paginas web,diseño y desarrollo de páginas web,diseños de paginas web,diseños de páginas web,diseños de paginas web bogota,diseños de paginas web creativas,diseños de paginas web en bogota,diseños paginas web,disñeo paginas web,lista empresas dedicadas al diseño de paginas web en bogota,mejores diseñadores de paginas web bogota,precio de diseño de paginas web en bogota colombia";
		        $meta_descripcion="Diseño de páginas web con orientación a resultados. Soporte anual a través de nuestro avanzado sistema de Helpdesk. Adaptabilidad a dispositivos móviles.";
	        }elseif($_REQUEST['content']=='pagina-web'){
		        $meta_titulo="Página Web - Diseño, Implementación y Soporte";
		        $meta_keywords="abrir mi pagina web,construccion pagina web,costo de pagina web,costo de una pagina web,costo general pagina web,costos de una pagina web,cotizacion pagina web,cotizar pagina web colombia,cotizar una pagina web,creacion de pagina web,creación de pagina web,creacion de una pagina web,creadores de pagina web,cuanto cuesta elaborar una pagina web,cuanto cuesta una pagina web,cuanto cuesta una pagina web en colombia,cuanto me cuesta una pagina web,cuanto vale una pagina web super completa,desarrollo página web,diseña pagina web,diseñadores de pagina web,diseñadores pagina web,diseñadores pagina web colombia,disenar pagina web,diseñar pagina web,diseño de pagina,diseño de página,diseno de pagina web,diseño de pagina web,diseño de página web,diseño de pagina web bogota,diseno pagina web,diseño pagina web,diseño página web,diseño pagina web precio,diseños de pag web,diseños de pagina,disenos de pagina web,diseños de pagina web,diseños pagina web,elaboracion pagina lweb,elaboracion pagina web,html pagina web,necesito comprar una pagina web,necesito pagina web,necesito una pagina web,pag web,página web,pagina web administrable,pagina web bogota,pagina web colombia,pagina web con carrito de compras,pagina web corporativa,pagina web corto tiempo,pagina web economica,pagina web economica en colombia,pagina web en horas,pagina web en html,pagina web multilenguaje,pagina web para empresas,pagina web para mi negocio,pagina webs,precio creacion pagina web colombia,precio de pagina web sencilla,precio pagina web,presupuesto de pagina web,presupuesto pagina web,propuestas de cotizacion de pagina web,publicar pagina web,valor pagina web,valor pagina web colombia";
		        $meta_descripcion="Diseñamos, desarrollamos e implementamos su página web con orientación a resultados, adaptabilidad a dispositivos móviles y soporte anual a través de nuestro avanzado sistema helpdesk.";
	        }elseif($_REQUEST['content']=='diseno-web'){
	        	   $meta_titulo="Diseño Web Corporativo";
	        	   $meta_keywords="diseño de web,diseñadores web,diseñador web,diseños web,precios diseño web,empresas de diseño web,empresa de diseño web,presupuesto diseño web,diseño web precios,empresa diseño web,empresas diseño web,diseño web precio,diseño web en colombia,diseño web multimedia,diseño wed,diseño web colombia,diseñadores de web,diseno web,disño web,servicios de diseño web,diseño web bogotá,diseño web en bogotá,disenador web,disenadores web,disenador web freelance,diseñador de pagina web,diseñador de web,diseño web en bogota,diseño web a medida,diseño web y posicionamiento,diseño web posicionamiento,diseño web bogota,diseño web empresarial,empresas de diseno web bogota,empresa de diseño web en bogota,planes diseño web,diseñadores web freelance,diseño y posicionamiento web,paginas de diseñadores web,diseñador web bogota,diseno web bogota,diseñadores web bogota,diseño de portales web,diseñadores web colombianos,diseñao web,diseño web diagramacion,diseño web htlm,diseños web particular,cual es la mejor empresa de diseño web bogota,cual es la mejor empresa de diseño web en bogota,diseño para sitios web corporativos,empresas en diseño web,diseño web bogota imagina,diseñador web bogotá,diseño de una web,diseño para web,servicio diseño web,diseño web marketing,creacion y diseño web,dsieño web,diseño web y marketing,lideres en diseño web";
		        $meta_descripcion="Diseño Web Corporativo. Diseñamos y desarrollamos con orientación a resultados. Soporte anual a través de nuestro avanzado sistema helpdesk.";
	        }elseif($_REQUEST['content']=='sitios-web'){
		        $meta_titulo = "Diseño, Desarrollo e Implementación de Sitios Web";
		        $meta_keywords = "diseño de sitios web,diseño sitio web,diseño sitios web,diseño de sitio web,diseño de un sitio web,desarrollo sitios web,desarrollo de sitios web,sitios de internet,desarrollo sitio web,diseños de sitios web,diseñador de sitios web,diseñadores de sitios web,planes web,paginas y sitios web,valor de sitio web,sitios web y paginas web,cotizacion de un sitio web,cotizacion sitio web doc,diseño de sitios web bogota,sitio web,creacion de sitio web,sitios de web,cotizar sitio web,precios sitios web dinamicos,";
		        $meta_descripcion="Diseño, desarrollo e implementación de sitios web con orientación a resultados. Adaptabilidad a dispositivos móviles y tabletas. Soporte anual a través de nuestro avanzado sistema helpdesk.";
	        }elseif($_REQUEST['content']=='aplicaciones-web'){
		        $meta_titulo = "Desarrollo de Aplicaciones Web";
		        $meta_keywords = "diseño de aplicaciones web,desarrollo de aplicaciones web,diseño aplicaciones web,programadores web bogota,diseñadores de aplicaciones web";
		        $meta_descripcion = "Desarrollo de aplicaciones web a la medida, desarrolladas con las últimas técnicas. Orientación a resultados. Adaptabilidad a tabletas y teléfonos inteligentes. Soporte a través de nuestro novedoso sistema helpdesk.";
	        }elseif($_REQUEST['content']=='mantenimiento-de-sitios-web'){
		        $meta_titulo = "Mantenimiento de Sitios Web";
		        $meta_keywords = "administracion paginas web,servicios paginas web,mantenimiento paginas web,servicio paginas web,mantenimiento de paginas web,webmaster bogota,editar una pagina web,administracion de paginas web,edicion de pagina web bogota,monitoreo de paginas web en bogota,necesito alguien que paneje paginas web,actualizacion de paginas web bogota,administradores paginas web corporativas,mantenimiento a paginas web,asesoria y edicion de paginas web";
		        $meta_descripcion = "Nuestra compañía administra y optimiza el funcionamiento de su sitio web para incrementar sus resultados. Adaptabilidad a dispositivos móviles. Soporte a través de nuestro avanzado sistema helpdesk.";
	        }elseif($_REQUEST['content']=='paginas-web-moviles'){
		        $meta_titulo = "Páginas Web Adaptables a Tabletas y Teléfonos Inteligentes";
		        $meta_keywords = "pagina web para movil,pagina web para moviles,paginas web moviles,paginas web para movil,diseño web para dispositivos moviles,diseño web responsive,paginas web para dispositivos moviles,diseño web movil bogota,pagina web movil";
		        $meta_descripcion = "No se quede atrás. Si quiere que su sitio sea eficiente y genere verdaderos resultados debe adaptarse a tabletas y teléfonos inteligentes.";
	        }elseif($_REQUEST['content']=='tiendas-virtuales'){
		        $meta_titulo = "Tiendas Virtuales y Sistemas ECommerce";
		        $meta_keywords = "diseño de tiendas virtuales bogota,creacion de una tienda web en colombia,pagina web con pagos en linea,diseño pagina web tienda virtual,modulo de compras pagina web,paginas web compras";
		        $meta_descripcion = "Desarrollamos e implementamos poderosas soluciones de Ecommerce a la medida de sus necesidades y con las características de sus clientes.";
	        }elseif($_REQUEST['content']=='social-media'){
	        	$meta_titulo = 'Estrategias de Social Media';
		        $meta_descripcion = 'Estrategias en redes sociales para impulsar su marca y generar interacciones que incrementen los índices de generación de clientes potenciales.';
		        $meta_keywords = 'Social Media,community managers,empresas de marketing,social media marketing,marketing en redes sociales,redes sociales para empresas,marketing digital';
	        }elseif($_REQUEST['content']=='email-marketing'){
	        	$meta_titulo = 'Email Marketing';
		        $meta_descripcion = 'Envio de correo electrónico masivo con altos índices de entrega y seguimiento de entregabilidad, lectura e interacción a cada contacto.';
		        $meta_keywords = 'Email Marketing,correo masivo,envio masivo de correos,mensajes masivos,campañas de email marketing,email marketing colombia,publicidad por correo electronico';
	        }elseif($_REQUEST['content']=='marketing-en-buscadores'){
	        	$meta_titulo = 'Marketing en buscadores';
		        $meta_descripcion = 'Campañas de posicionamiento en buscadores que se adaptan a sus objetivos estratégicos y se centran en la generación de nuevos contactos.';
		        $meta_keywords = 'posicionamiento paginas web,posicionar mi pagina web,posicionamiento paginas web bogota,expertos en adwords y pag web bogota,posicionamiento web';
	        }elseif($_REQUEST['content']=='planificacion-estrategica'){
	        	$meta_titulo = 'Estrategias de Marketing Digital';
		        $meta_descripcion = 'Un plan de acción que base la ejecución de su estrategia en la obtención de metas específicas, es un aliado que le evitará desgastarse en tiempo y dinero sin generar resultados.';
		        $meta_keywords = 'agencia de diseño web,agencia web,agencias de diseño web,agencia diseño web,agencia de web,agência web design,agencias de desarrollo web,agencia web marketing,web agencia,agencia digital,agencia digitales,agencias digitales,agencia marketing digital,agência de marketing digital,agencias marketing digital,marketing digital agencia,asesorias montaje pagina web';
	        }elseif($_REQUEST['content']=='hosting-y-dominios'){
	        	$meta_titulo = 'Hosting en Colombia y Registro de Dominios';
		        $meta_descripcion = 'Sus servicios de infraestructura no deben der una limitante a la hora de implementar nuevas estrategias en el marco de su estrategia digital.';
		        $meta_keywords = 'hosting colombia, hosting y dominio, dominios .com, servidor web, alojamiento web';
	        }elseif($_REQUEST['content']=='portafolio'){
	        	$meta_titulo = 'Portafolio de Proyectos de Marketing Digital';
		        $meta_descripcion = 'Una larga trayectoria y cientos de proyectos realizados garantizan nuestro compromiso con sus resultados.';
		        $meta_keywords = 'portafolio closer design, ejemplos paginas web, ejemplos desarrollo web, proyectos web, proyectos de marketing digital, landing page, pagina de aterrizaje';
	        }elseif($_REQUEST['content']=='contactenos'){
	        	$meta_titulo = 'Asesoría en Marketing Digital';
		        $meta_descripcion = 'Contáctenos para poder asesorarlo en la construcción de su estrategia de marketing digital, desarrollo web, email marketing, marketing buscadores, estrategia de social media.';
		        $meta_keywords = 'desarrollo web, agencia digital, email marketing, social media, marketing en buscadores';
	        }elseif($_REQUEST['content'] == 'planes'){
	        	$meta_titulo = 'Planes de Hosting';
		        $meta_descripcion = 'Alojamiento de clase mundial para sus sitios y aplicaciones web, con opciones escalables y ajustadas a la medida de cada necesidad.';
		        $meta_keywords = 'hosting colombia, hosting y dominio, dominios .com, servidor web, alojamiento web';
	        }else{
	        	$meta_titulo = 'Desarrollo web';
		        $meta_descripcion = 'Somo efectivos en la producción de resultados a través de nuestras estrategias de marketing digital.';
		        $meta_keywords = 'agencia digital,Email Marketing,diseno de paginas web,marketing online,community managers,marketing digital,diseno paginas web,desarrolladores paginas web,paginas web colombia';
	        }
        ?>